### ISSUE TITLE
Passing `&ImString` triggers a non-null assertion, undefined behavior in safe code.

### ISSUE THREAD

**Issue by alula** [Gekkio/imgui-rs#389]
**Describe the bug**
Looks like passing a double string reference results in undefined behavior in safe code.

**To Reproduce**
```rust
let title = &ImString::new("something");
let contents = &ImString::new("something");
Window::new(title)
    .build(ui, || {
        ui.text(contents);
    });
```

Application immediately exits once imgui tries to dereference a double pointer as `char*`.

```
third-party/imgui/imgui.cpp:5477: bool ImGui::Begin(const char*, bool*, ImGuiWindowFlags): Assertion `name != __null && name[0] != '\0'' failed.
```

**Expected behavior**
The string reference is handled correctly and there's no undefined behavior in safe code.

**Please describe your environment**

Latest snapshot at time this issue was written: a990a538b66cb67dba3a072bf299b6a51c001447

```toml
imgui = {git = "https://github.com/Gekkio/imgui-rs.git", rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
imgui-gfx-renderer = {git = "https://github.com/Gekkio/imgui-rs.git", rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
imgui-winit-support = {git = "https://github.com/Gekkio/imgui-rs.git", default-features = false, features = ["winit-23"], rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
```
