### ISSUE TITLE
Crashed when resize the window corner

### ISSUE THREAD

**Issue by molinla** [Gekkio/imgui-rs#734]
**Describe the bug**
I'm running the main examples, such as `hello_world` or other examples. They all crashed when I resized the window rapidly at the window corner.

**To Reproduce**

1. I use  `windows powershell` to run example.
``` powershll
cargo run --package imgui-examples  --example hello_world
```
2. Move the mouse to the corner of the window and then resize the window rapidly.
3. Here is the error output.
``` txt
error: process didn't exit successfully: `target\debug\examples\hello_world.exe` (exit code: 0xc000041d)
```

**Expected behavior**
The window should resize smoothly and should not crash.

**Screenshots**
![crashed when resize](https://github.com/imgui-rs/imgui-rs/assets/61045398/4b338b5d-b3fd-4be6-b766-cd0cf5bcb57c)

**Please describe your environment**

- I copied the `hello world` example into a new cargo project. This is the content of my Cargo.toml file.

  ``` toml
  [package]
  name = "imgui"
  version = "0.1.0"
  edition = "2021"

  # See more keys and their definitions at https:doc.rust-lang.org/cargo/reference/manifest.html

  [dependencies]
  image = "0.24.6"
  copypasta = "0.8"
  glium = { version = "0.32.1", default-features = true }
  imgui = { version = "0.11.0", features = ["tables-api"] }
  imgui-glium-renderer = "0.11.0"
  imgui-winit-support = "0.11.0"
  ```
- My System information
  | Name  | Infomation |
  |----------|-----------|
  | System  | Microsoft Windows 11 Pro    |
  | System Version | 10.0.22621.1928 (Win11 22H2 2022 Update)  |
  | GPU   | nVIDIA GeForce RTX 3060 Laptop  |
  |  DirectX | DirectX v12 |

- My RUST Version `stable`, `rustc 1.70.0 (90c541806 2023-05-31)`
- That's all i have known.

**Other information**
 &nbsp;&nbsp; I tried compiling the source code and `running it on different operating systems`. Since I don't have physical machines, I had to use `virtual machines`. I tested it on `Windows 10` and `Windows 7`, but the execution was very slow and laggy, possibly due to the lack of a dedicated graphics card, making it `difficult for me to perform proper testing`.
